### ISSUE TITLE
Requesting to add "Seclilc" to the list of Information Security focused streamers

### ISSUE THREAD

**Issue by d3vaashish** [infosecstreams/infosecstreams.github.io#134]
Could you please add "Seclilc" to the list of Information Security focused streamers
 
Twitch: https://www.twitch.tv/seclilc
YouTube: https://www.youtube.com/@seclilc
Twitter: https://twitter.com/seclilc
Instagram: https://www.instagram.com/seclilc/
GitHub: https://github.com/seclilcc

**Comment by goproslowyo** [comment]
- [x] [Already done](https://github.com/infosecstreams/infosecstreams.github.io/pull/131/commits/38773a8772198991e72443a7f03e0e9ecacf0082)
