### ISSUE TITLE
Include Streamer Language in the List

### ISSUE THREAD

**Issue by Tabris83** [infosecstreams/infosecstreams.github.io#59]
I would be a good idea to include the "Broadcast" language in the list.

https://dev.twitch.tv/docs/api/reference#get-channel-information

**Comment by goproslowyo** [comment]
Agreed! Thanks -- we've been kicked around ideas on how to handle both stream language and how to check if someone if actually streaming infosec content, as opposed to e.g. Valorant or Overwatch, as well. Suggestions, improvements, PRs welcome!

**Comment by goproslowyo** [comment]
I think we can take care of this with the Twitch `streams` API. It returns to us both the stream `language` and `game_name` so we can hook into this information [in our automation](https://github.com/infosecstreams/StreamStatus/blob/c14d433070ec568c1e9ed659303b56434ea3511e/StreamStatus.go#L166-L180).

**Comment by Tabris83** [comment]
I've been looking through the Twitch API to see if it's possible to search by tag as well.
that way to be included on the list all you need to do is put #CyberSecurity or #InfoSec in your Title or Stream Tags.

It doesn't look like tags are returned by the API yet but there is a Uservoice for it
https://twitch.uservoice.com/forums/310213-developers/suggestions/40154632-add-filtering-by-tag-to-endpoints-that-return-stre

**Comment by goproslowyo** [comment]
Thank you very much @Douile I plan to review this by Friday or so. Just need some spare time.

**Comment by Douile** [comment]
Nw, will give me time to clean some things up

**Comment by goproslowyo** [comment]
@Tabris83 what do you think?
