### ISSUE TITLE
still can't fully approve and merge pull requests

### ISSUE THREAD

**Issue by 0xLGG** [infosecstreams/infosecstreams.github.io#8]

**Comment by goproslowyo** [comment]
@0xLGG Hey sorry man I just saw this. Can you check to see if you have any pending invitations to accept? https://github.com/orgs/infosecstreams/invitation

**Comment by 0xLGG** [comment]
Hey @goproslowyo.

I was away and the Invitation has expired. Had to activate 2FA. It is now all ready. Can you send another Invitation?

Thx

**Comment by goproslowyo** [comment]
@0xLGG No problem man -- hope you enjoyed the time :). I resent the invitation again!
